# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

trigger:
- azure_pipe_test_feedme

pool:
  vmImage: 'macos-latest'

steps:
- script: /usr/local/bin/pod install
  displayName: 'pod install using a script'

- task: CmdLine@2
  inputs:
    script: 'npm install -g firebase-tools'
      
- task: CocoaPods@0
  inputs:
    forceRepoUpdate: true
    projectDirectory: '$(system.defaultWorkingDirectory)'
  displayName: 'pod install using the CocoaPods task with a forced repo update and a custom project directory'

- task: InstallAppleProvisioningProfile@1
  inputs:
    provisioningProfileLocation: 'secureFiles'
    provProfileSecureFile: 'testpn_ios_profile.mobileprovision'

- task: InstallAppleCertificate@2
  inputs:
    certSecureFile: 'std_Certificates.p12'
    certPwd: '$(certpwd)'
    keychain: 'temp'

- task: Xcode@5
  inputs:
    actions: 'build'
    xcWorkspacePath: 'FeedMe.xcworkspace'
    scheme: 'FeedMe'
    packageApp: true
    signingOption: 'manual'
    signingIdentity: '$(APPLE_CERTIFICATE_SIGNING_IDENTITY)'
    provisioningProfileUuid: '$(APPLE_PROV_PROFILE_UUID)'
    useXcpretty: false
    

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      PROJECT_NAME="FeedMe"
      BUILD_DIR="Output/$(SDK)/$(Configuration)"
      
      firebase appdistribution:distribute "${BUILD_DIR}/${PROJECT_NAME}".ipa --app 1:251123050848:ios:1205bf14193485d455d605 --groups test_group

