# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

trigger:
- azure_pipe_test_feedme

pool:
  vmImage: 'macos-latest'

steps:
- script: /usr/local/bin/pod install
  displayName: 'pod install using a script'

- task: CmdLine@2
  inputs:
    script: |
      npm install -g firebase-tools


- task: CocoaPods@0
  inputs:
    forceRepoUpdate: true
    projectDirectory: '$(system.defaultWorkingDirectory)'
  displayName: 'pod install using the CocoaPods task with a forced repo update and a custom project directory'

- task: InstallAppleProvisioningProfile@1
  inputs:
    provisioningProfileLocation: 'secureFiles'
    provProfileSecureFile: 'testpn_ios_profile.mobileprovision'

- task: InstallAppleCertificate@2
  inputs:
    certSecureFile: 'std_Certificates.p12'
    certPwd: '$(certpwd)'
    keychain: 'temp'



- task: CopyFiles@2
  inputs:
    contents: '**/*.ipa'
    targetFolder: '$(build.artifactStagingDirectory)'
    overWrite: true

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(build.artifactStagingDirectory)/output/$(sdk)/$(configuration)' 
    artifactName: 'drop' 
    publishLocation: 'Container'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      PROJECT_NAME="FeedMe"
      BUILD_DIR="$(build.artifactStagingDirectory)/output/$(sdk)/$(configuration)"
      
      firebase appdistribution:distribute "${BUILD_DIR}/FeedMe".ipa --app 1:251123050848:ios:1205bf14193485d455d605 --groups test_group --token "1//0gWhDnpyydr90CgYIARAAGBASNwF-L9IrEFBxHa9aDMWzqdCmIP9JFEvsPi0dxkMJxvo-rj9Z_EraXVD6-egeLf6H5bOvEkyduKw"

