# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

trigger:
- azure_pipe_test_feedme

pool:
  vmImage: 'macos-latest'

steps:
- script: /usr/local/bin/pod install
  displayName: 'pod install using a script'

- task: CocoaPods@0
  displayName: 'pod install using the CocoaPods task with defaults'

- task: CocoaPods@0
  inputs:
    forceRepoUpdate: true
    projectDirectory: '$(system.defaultWorkingDirectory)'
  displayName: 'pod install using the CocoaPods task with a forced repo update and a custom project directory'

- task: InstallAppleProvisioningProfile@1
  inputs:
    provisioningProfileLocation: 'secureFiles'
    provProfileSecureFile: 'testpn_ios_profile.mobileprovision'

- task: InstallAppleCertificate@2
  inputs:
    certSecureFile: 'std_Certificates.p12'
    certPwd: '$(certpwd)'

- task: Xcode@5
  inputs:
    actions: 'build'
    configuration: 'Release'
    sdk: 'iphoneos'
    xcWorkspacePath: 'FeedMe.xcworkspace'
    scheme: 'FeedMe'
    packageApp: true
    exportArgs: 'Automatic Export Test'
    signingOption: 'auto'
    teamId: 'UY48DQR2XB'
    

